# -*- coding: utf-8 -*-
"""Machine Problem no.1 CSST102.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXO2leTWMhauWpSFAyp8wZPhb2zhklks
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("iris_dataset.csv")
print(df.head(5))

print(df.info)
print(df.describe())
print(df['species'].value_counts())

df['sepal length (cm)'].hist()
plt.title("Sepal Length Distribution")
plt.show()

sns.scatterplot(data=df, x="petal length (cm)", y="petal width (cm)", hue="species")
plt.title("Petal Length vs. Petal Width")
plt.show

#What is the input (features)?
#-Measurements of the iris flowers
#What is the output (label)?
#-Species of the iris flower
#Is this supervised or unsupervised learning?
#-Supervised as the dataset contains labeled examples where each measurement of the flowers are labeled